### ISSUE TITLE
v8 indexing errors in logs

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/The-Starter-Kit#60]
I get these errors in the logs while I'm trying to install the starter kit

```
2019-02-08 17:43:17,390 [P21756/D42/T219] ERROR  Umbraco.Examine.UmbracoContentIndex - Error indexing queue items
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2..ctor(IDictionary`2 dictionary, IEqualityComparer`1 comparer)
   at Examine.LuceneEngine.Providers.LuceneIndex.AddDocument(Document doc, ValueSet valueSet, IndexWriter writer) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 669
   at Umbraco.Examine.UmbracoExamineIndex.AddDocument(Document doc, ValueSet valueSet, IndexWriter writer) in C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Examine\UmbracoExamineIndex.cs:line 167
   at Examine.LuceneEngine.Providers.LuceneIndex.ProcessIndexQueueItem(IndexOperation op, IndexWriter writer) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 1194
   at Examine.LuceneEngine.Providers.LuceneIndex.ProcessQueueItem(IndexOperation item, IndexWriter writer) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 1013
   at Examine.LuceneEngine.Providers.LuceneIndex.ForceProcessQueueItems(Boolean block) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 872
```

**Comment by Shazwazza** [comment]
oops wrong repo
